### ISSUE TITLE
we can get `k` in UNG2R from the size of tau, remove k from interface?

### ISSUE THREAD

**Issue by langou** [tlapack/tlapack#103]
https://github.com/tlapack/tlapack/blob/85d2fe156463f11d5e2b35abe167acd98dbbafd0/include/lapack/ung2r.hpp#L48

In UNG2L, @yuxincai11 proposes to get `k` from the size of tau. So `k` gets removed from the  interface and is obtained by the size of tau.

**Comment by weslleyspereira** [comment]
My opinion:
- If we have tau and T on the interface, it makes sense to extract k from them.
- If we don't have them on the interface, we should probably have k on the interface.

**Comment by weslleyspereira** [comment]
Same as #180 .
