### ISSUE TITLE
Tests fail to build: error: no member named 'lartg' in namespace 'lapack'

### ISSUE THREAD

**Issue by yurivict** [tlapack/tlapack#111]
```
In file included from /disk-samsung/freebsd-ports/math/tlapack/work/.build/_deps/testblas-src/src/test_infNaN.cpp:14:
In file included from /disk-samsung/freebsd-ports/math/tlapack/work/tlapack-77352a9/include/legacy_api/blas.hpp:13:
/disk-samsung/freebsd-ports/math/tlapack/work/tlapack-77352a9/include/optimized/wrappers.hpp:192:15: error: no member named 'lartg' in namespace 'lapack'
    ::lapack::lartg( a, b, &c, &s, &r );
    ~~~~~~~~~~^
/disk-samsung/freebsd-ports/math/tlapack/work/tlapack-77352a9/include/optimized/wrappers.hpp:212:15: error: no member named 'lartg' in namespace 'lapack'
    ::lapack::lartg( a, b, &c, &s, &r );
    ~~~~~~~~~~^
2 errors generated.
```

Rev,77352a9
lapackpp-2022.05.00
clang-13.1
FreeBSD 13.1

**Comment by weslleyspereira** [comment]
Thanks! I am working on that now. Please watch https://github.com/tlapack/testBLAS/pull/2. This was probably caused by a recent change of compiler flags in #86.

**Comment by weslleyspereira** [comment]
[yurivict](https://github.com/yurivict), can you please test it again with the new version on testBLAS. I recommend you erase your build directory so that the CMake script can download the newer version. Thanks!

**Comment by yurivict** [comment]
@weslleyspereira Revision of the project didn't change and the error is still there.

**Comment by weslleyspereira** [comment]
Ah! Now I see the problem. You say you are using lapackpp-2022.05.00. `lartg` is not part of LAPACK++. Please, consider using https://bitbucket.org/weslleyspereira/lapackpp/branch/tlapack. I will prepare a PR in the LAPACK++ repository.

**Comment by yurivict** [comment]
I work on the FreeBSD port. lapackpp is another port, so it would be difficult to switch to a custom lapackpp fork in this context.

I'll wait for your PR to make its way into lapackpp.

**Comment by weslleyspereira** [comment]
Thanks for explaining, and for your brief introduction! Please, mind that some of the design choices in \<T\>LAPACK may change in the near future. All contributions are welcome on our side.

**Comment by weslleyspereira** [comment]
Hi, lartg is now part of LAPACK++. Also, their main development migrated from Bitbucket to Github: https://github.com/icl-utk-edu/lapackpp.
