### ISSUE TITLE
__ reserved

### ISSUE THREAD

**Issue by mgates3** [tlapack/tlapack#117]
This is a bit pedantic, but any identifier containing `__` (double underscore) or beginning with `_` (underscore) is reserved in C++. So all the headers guards should be fixed, easiest just by removing the __:
```
__TLAPACK_LAPACKPP_WRAPPERS_HH__
change to
TLAPACK_LAPACKPP_WRAPPERS_HH
```
and internal variables should have trailing instead of leading underscores:
```
auto _x = legacy_vector(x);
change to
auto x_ = legacy_vector(x);
```
See https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

**Comment by weslleyspereira** [comment]
Actually, thanks @mgates3 for explaining this better!
