### ISSUE TITLE
List of finished routines in readme

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#131]
I think it would be good to have a list of all the lapack methods (not their routine name, but their actual name, like banded LU) in the readme. Then we can add an icon whether or not it is actually available in <T>LAPACK.

That would be good for us to track progress. And also good for any potential early adopters. I certainly appreciate it when i want to use a WIP library when they list what has and has not been implemented.

**Comment by weslleyspereira** [comment]
Great idea! Thanks. We don't have it wrote anywhere.
