### ISSUE TITLE
Replace if( "some-constexpr" ) by IF_CONSTEXPR( "some-constexpr" )

### ISSUE THREAD

**Issue by weslleyspereira** [tlapack/tlapack#16]
It seems a good idea to replace `if( "some-constexpr" )` by `IF_CONSTEXPR( "some-constexpr" )`, where

```c++
#if __cplusplus >= 201703L
    #define IF_CONSTEXPR( expr ) if constexpr( expr ) // C++17 or higher
#else
    #define IF_CONSTEXPR( expr ) if( expr ) // C++14
#endif
```

This will enable the nice feature of C++17 when available. `if constexpr` is not for optimization, it is for improving code semantics. By using `if constexpr`, we assure the compiler only instantiates the correct code block. See the discussion here: https://stackoverflow.com/questions/54545565/if-constexpr-vs-if-in-light-of-compiler-optimization-and-code-performance

**Comment by weslleyspereira** [comment]
See also the discussion here: https://stackoverflow.com/questions/54545565/if-constexpr-vs-if-in-light-of-compiler-optimization-and-code-performance

**Comment by thijssteel** [comment]
I don't see how this would benefit us. The main advantage of if constexpr, is if you want to do something like:

```
if constexpr(std::is_same<T, std::complex<real_t>>::value){
    // Do something that only compiles for complex types
} else {
   // Do something that only compiles for real types
}
```

But we can't do that with this definition, because it wouldn't compile for c++14. See also my comment on PR #34.

**Comment by weslleyspereira** [comment]
Hi. Yes, I agree. I was thinking on marking the `if` just to say it is a conditional always evaluated at compile time. But this is not always true, it depends on the compiler and compiler flags for C++14.

(If we had the "ideas" page by the time I created this issue, it would be there and not here. It is just an idea that it is not good 😊)
