### ISSUE TITLE
remove `k` from the interface from ung2r, get `k` from size of tau

### ISSUE THREAD

**Issue by langou** [tlapack/tlapack#180]
https://github.com/tlapack/tlapack/blob/0377a585a2e15653e4e6006a4aae53297b7f3ba6/include/tlapack/lapack/ung2r.hpp#L40-L45

Let us remove the parameter `k` from the interface from `ung2r`, we can get the parameter `k` from the size of `tau`.

This is akin to what @yuxincai11 did for ungl2. See
https://github.com/tlapack/tlapack/blob/0377a585a2e15653e4e6006a4aae53297b7f3ba6/include/tlapack/lapack/ungl2.hpp#L36-L40

Note: also we need to write a tester for geqr2+ung2r

@maameasamoah17

**Comment by maameasamoah17** [comment]
I have made the changes.
