### ISSUE TITLE
should pivot vector be a vector_idx_t or vector_t?

### ISSUE THREAD

**Issue by maameasamoah17** [tlapack/tlapack#182]
https://github.com/tlapack/tlapack/blob/08358e4c9cb519597d919ca7f3173262e74cb6e8/include/tlapack/lapack/getrf_recursive.hpp#L56

vector_t makes it sounds like a vector of real or complex number
maybe we want to change the name to indicate that we expect a vector of index?

Happy to propose a PR.

**Comment by weslleyspereira** [comment]
Hi! Hm... yes, I understand the problem.

Two steps to this solution:
1. Maybe `idxVector_t` is a better name than `vector_t`. So, a PR would solve it.
2. We shall add a comment about the naming conventions for the templates at CONTRIBUTING.md. We still don't have a section about naming conventions. We could start one with the proposed PR.
