### ISSUE TITLE
which swap should we use tlapack/blas/swap.hpp or std::swap ?

### ISSUE THREAD

**Issue by maameasamoah17** [tlapack/tlapack#183]
which swap should we use tlapack/blas/swap.hpp or std::swap ?
getrf_recursive seems to include tlapack/blas/swap.hpp and use std::swap

See: https://github.com/tlapack/tlapack/blob/08358e4c9cb519597d919ca7f3173262e74cb6e8/include/tlapack/lapack/getrf_recursive.hpp#L17
https://github.com/tlapack/tlapack/blob/08358e4c9cb519597d919ca7f3173262e74cb6e8/include/tlapack/lapack/getrf_recursive.hpp#L97
https://github.com/tlapack/tlapack/blob/08358e4c9cb519597d919ca7f3173262e74cb6e8/include/tlapack/lapack/getrf_recursive.hpp#L121

Do we use std::swap to swap two scalars and tlapack/blas/swap.hpp to swap vectors?

I would be happy to propose a PR if someone lets me know what to do

**Comment by weslleyspereira** [comment]
Hi! 

Although they have the same name, `std::swap` and `tlapack::swap` do different things.

- `std::swap` takes 2 objects of the same type T and swaps either (1) their values, if T is a basic type; or (2) all their attributes, if T is a class.

- `tlapack::swap` takes 2 vectors of types `vectorX_t` and `vectorY_t` and swaps their entries.

Now, let me take the questions:

> which swap should we use tlapack/blas/swap.hpp or std::swap ?
> getrf_recursive seems to include tlapack/blas/swap.hpp and use std::swap

Use `tlapack::swap` whenever you want to swap the entries between two arrays.
Currently, `std::swap` is only used in \<T\>LAPACK to avoid a code like 
```c++
// Swaps a and b. Equivalent to std::swap(a,b)
T aux = a;
a = b;
b = aux;
```

> Do we use std::swap to swap two scalars and tlapack/blas/swap.hpp to swap vectors?

Yes, that is how we currently use those functions.

**Comment by langou** [comment]
Thanks for explaining @weslleyspereira. Maybe we add this to the "coding style guide".
