### ISSUE TITLE
Suggested interface change for gelqf

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#187]
Right now the routine gelqf has the signature:

gelqf( A, TT, opts)

TT stores the upper triangular factors and also serves as workspace. Allowing them to be reused later.

I don't like this for two reasons:
- It makes the interface gelqf incompatible with gelq2 and makes the legacy interface more difficult
- TT depends on nb, which is an optional argument. Essentially, to make good code, this means that nb is no longer optional.

Proposed change:
- Make TT an optional argument and replace the mandatory interface with tau

**Comment by weslleyspereira** [comment]
I just looked at the code and it seems nb is the number of columns of TT. So, I don't see the point of having it anywhere in the interface.

As I said in another thread, I think it could be a good idea to make distinction between `gelqt( A, TT )` and `gelqf( A, tau )`.
