### ISSUE TITLE
workspace query, switch to function return instead of [in, out]

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#188]
I'm not a big fan of the current workspace queries

workspace queries now look something like this:
```cpp
    workinfo_t workinfo;
    foo_worksize( ..., workinfo );
    bar_worksize( ..., workinfo );
```

This does lead to compact code, but it does not read that well (at least to me). I would suggest that instead of an [in,out] reference, we have the function return the workinfo, so that we get something like this:

```cpp
    auto workinfo = foo_worksize(...);
    workinfo += bar_worksize(...);
```

This makes it more clear at a glance what the function is actually doing, it also makes it very clear whether we are adding the workspace together or taking the max.

If i recall correctly, this is how they were originally implemented so i'm not not sure why this was changed.

**Comment by weslleyspereira** [comment]
Hi. The change was due to this comment https://github.com/tlapack/tlapack/pull/128#issuecomment-1227493389, which is the design @mgates3 mentioned they were implementing (or maybe already implemented) in LAPACK++. It was a more conservative choice to align to the choice from LAPACK++.

I do not oppose to having workinfo in the return parameter. Moreover, I agree it is more intuitive.

**Comment by mgates3** [comment]
Yes, we use that design for GPU routines in LAPACK++, the big thing being we seemingly need to query both CPU and GPU workspace (at least, cuSolver has both in its interface). So far, CPU routines in LAPACK++ allocate their workspace internally.

Of course, in C++ you could return a std::pair of sizes if needed, but that makes things less clear (which is first)?

**Comment by thijssteel** [comment]
The current design in <T>LAPACK already uses a special struct for workspace anyway, so there would be no confusion about what is first.

**Comment by weslleyspereira** [comment]
I agree with @thijssteel. The first design of the workspace was returning integers. Then it made sense to follow the design in LAPACK++. However, I realized that we needed more than an integer to represent a workspace. The current design is already different from LAPACK++.
