### ISSUE TITLE
Testing: should we remove preallocations?

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#204]
While writing a few tests, I noticed a potential problem.

We often write something like this in a test:

```
    workinfo_t workinfo = {};
    geqr2_worksize(A, tau, workinfo);
    ung2r_worksize(Q, tau, workinfo);
    unm2r_worksize(side, trans, A, tau, C, workinfo);

    // Workspace allocation:
    vectorOfBytes workVec;
    workspace_opts_t<> workOpts(alloc_workspace(workVec, workinfo));

    // QR factorization
    geqr2(A, tau, workOpts);
    ...
```

A situation where the workspace query of one of these is incorrect might still pass the test because the required workspace of other routines is large enough. The simplest solution is to make it standard practice not to preallocate workspace in the tests and just calling the routines, i.e.

```
geqr2(A, tau);
```

As an added bonus, the test code is a bit simpler.

What do you think?

**Comment by weslleyspereira** [comment]
Good idea! I agree.
