### ISSUE TITLE
Const matrices/vectors are still modifyable

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#212]
Currently the access operators in our matrices are defined as follows:

```c++
    inline constexpr T& operator()(idx_t i, idx_t j) const noexcept
    {
        return (layout == Layout::ColMajor) ? ptr[i + j * ldim]
                                            : ptr[i * ldim + j];
    }
```

Because the function is defined as `const`, we can do something like this

```c++
template< class matrix_t>
void foo( const matrix_t& A  ){
     A(0,0) = 0;
}
```
i.e. we can modify a const matrix. While valid c++ syntax, I found some sources that consider this bad practice.
In the scientific software course I'm TA for, the students are taught to do something like this:

```c++
    inline constexpr T& operator()(idx_t i, idx_t j) noexcept
    {
        return (layout == Layout::ColMajor) ? ptr[i + j * ldim]
                                            : ptr[i * ldim + j];
    }

    inline constexpr const T& operator()(idx_t i, idx_t j) const noexcept
    {
        return (layout == Layout::ColMajor) ? ptr[i + j * ldim]
                                            : ptr[i * ldim + j];
    }
```

If the matrix is const, this returns a const reference so that it cannot be modified.

The change is not nearly that simple though. We would also need to change the plugins, because a slice of a const matrix would need to return a const slice, ... I think there can be some discussion whether or not it's worth the effort.

**Comment by weslleyspereira** [comment]
I agree this data type does not follow the best practices. Thanks. I learned that too, and now I am ashamed for not writing the better design in place from start. I don't think it is that difficult, see #213.

One thing that we didn't do, on purpose, was to not protect the attributes of legacy matrices and vectors. Those are supposed to be more flexible data types, that will ease the development. That was my thought when I first wrote them.
