### ISSUE TITLE
Real matrix type

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#219]
To my knowledge, there is no way to turn a matrix type into a real matrix type. Something like:
```c++
using real_matrix_t = real_t<matrix_t>;
```
Does this require extending all the plugins or are there better ways?

**Comment by weslleyspereira** [comment]
This is something related to how we access information in the matrix structure. Therefore, it is related to the data and not to the plugins. If we require that all data we support need to provide such a feature, then we could put it in the plugins. That is my understanding.

- For Eigen matrices, I think the answer is this: https://stackoverflow.com/a/22345247. I haven't tested it.
- On `mdspan`, one would need to define a "real type accessor".
- `legacyMatrix` doesn't provide this functionality.

**Comment by thijssteel** [comment]
I think you misunderstood me. I don't want a real type accessor of a specific matrix. In the svd algorithm (or at least the lvl 3 version I'm trying to implement), you need a real workspace matrix even for complex input. I want to define something like:
```c++
    Create<matrix_t> new_matrix;
    using real_matrix_t = real_t<matrix_t>;
    Create<real_matrix_t> real_new_matrix;
```
I don't need a real version of some given matrix, I need to transform the type `legacyarray<std::complex<float>>` into `legacyarray<float>`

**Comment by weslleyspereira** [comment]
Can you try https://github.com/tlapack/tlapack/pull/221? I still need to add the specializations for Eigen and mdspan. I prefer to wait for your feedback before doing that.
