### ISSUE TITLE
Compilation with Eigen fails locally

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#272]
The CI doesn't seem to struggle with this issue, but I fail to compile the library with Eigen.

I made sure to select the specified commit in the eigen repo (2873916f1ca24e3282bf6e0150545d34a16b5224)

The error message i get is:
```
[build] /home/thijs/Documents/Git/tlapack/test/src/test_larf.cpp:149:1:   required from here
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:391:13:   required for the satisfaction of ‘SliceableMatrix<matrix_t>’ [with matrix_t = Eigen::Matrix<std::complex<float>, -1, -1, 1, -1, -1>]
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:391:50:   in requirements with ‘const matrix_t& A’ [with matrix_t = Eigen::Matrix<std::complex<float>, -1, -1, 1, -1, -1>]
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:395:18: note: ‘tlapack::slice(A, (std::pair<int, int>)({0, 1}), (std::pair<int, int>)({0, 1}))’ does not satisfy return-type-requirement
[build]   395 |             slice(A, pair<int, int>{0, 1}, pair<int, int>{0, 1})
[build]       |             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:401:17: note: ‘tlapack::rows(A, (std::pair<int, int>)({0, 1}))’ does not satisfy return-type-requirement
[build]   401 |             rows(A, pair<int, int>{0, 1})
[build]       |             ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:407:17: note: ‘tlapack::cols(A, (std::pair<int, int>)({0, 1}))’ does not satisfy return-type-requirement
[build]   407 |             cols(A, pair<int, int>{0, 1})
[build]       |             ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:413:16: note: ‘tlapack::row(A, 0)’ does not satisfy return-type-requirement
[build]   413 |             row(A, 0)
[build]       |             ~~~^~~~~~
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:419:16: note: ‘tlapack::col(A, 0)’ does not satisfy return-type-requirement
[build]   419 |             col(A, 0)
[build]       |             ~~~^~~~~~
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:425:18: note: ‘tlapack::slice(A, 0, (std::pair<int, int>)({0, 1}))’ does not satisfy return-type-requirement
[build]   425 |             slice(A, 0, pair<int, int>{0, 1})
[build]       |             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] /home/thijs/Documents/Git/tlapack/include/tlapack/base/concepts.hpp:431:18: note: ‘tlapack::slice(A, (std::pair<int, int>)({0, 1}), 0)’ does not satisfy return-type-requirement
[build]   431 |             slice(A, pair<int, int>{0, 1}, 0)
[build]       |             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

No idea why it does not work.

**Comment by weslleyspereira** [comment]
Very awkward. What C++ compiler are you using? We do not test many compilers in the CI. Basically, GCC and Intel compilers.

**Comment by thijssteel** [comment]
GCC 11.4, i've also tried GCC 11.3 and GCC 12.1

**Comment by weslleyspereira** [comment]
I have been testing multiple versions of GCC in my machine as well. Never seen this problem. 

One idea: I created a `test_concepts.cpp`. Please add this test case to it:

```c++
TEST_CASE("Concept SliceableMatrix works as expected", "[concept]")
{
#ifdef TLAPACK_TEST_EIGEN
    using matrix_t = Eigen::Matrix<std::complex<float>, -1, -1, 1, -1, -1>;
    REQUIRE(SliceableMatrix<matrix_t>);
    
    matrix_t A;
    auto B = tlapack::slice(A, std::pair<int, int>{0, 1}, std::pair<int, int>{0, 1});
    REQUIRE(Matrix<decltype(B)>);
#endif
}
```

It should fail in your case. In my case, all tests pass. If it really fails in your case, I would like to know what type matrix B has.

**Comment by thijssteel** [comment]
It does fail, B has type `Eigen::Block<matrix_t, -1, -1, false>`

**Comment by weslleyspereira** [comment]
I have found the problem and could reproduce in my machine.

At compile time, the ADL (Argument-dependent lookup) tries to find to find the correct implementation of `size(Eigen::Block<Eigen::Matrix<std::complex<float>, -1, -1, 1, -1, -1>, -1, -1, false>)`. Since the argument of the function are in the namespace Eigen, it will first try to use `Eigen::size()`, which does not exists. Then, I thought it would try to use `std::size()` because the argument depends on `std::complex` (see https://en.cppreference.com/w/cpp/iterator/size implementation number (1)). I was wrong about it. So, we need to change the rules in the template specification of `tlapack::size()` in `eigen.hpp`.

Please, try #273.

**Comment by thijssteel** [comment]
I still get the same error, i've tried to get more verbose output from gcc but it only tells me that the return type is not satisfied.

**Comment by weslleyspereira** [comment]
Which OS are you using? I can try to run a Docker image to reproduce it.

**Comment by thijssteel** [comment]
:facepalm: i just found out my configuration is wrong.

If have eigen_DIR set to my local install, but cmake is still using the system install, which is 3.4.0. I don't know why it's not reading it correctly, i'll just fix it when i get my new laptop.
