### ISSUE TITLE
Use of optimized blas

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#287]
I just did a quick experiment to check if optimized blas is being used.

```c++

    using T = double;
    using matrix_t =
        tlapack::LegacyMatrix<T, std::size_t, tlapack::Layout::ColMajor>;

    std::cout << "<T>: " << tlapack::allow_optblas<T> << std::endl;
    std::cout << "<matrix_t>: " << tlapack::allow_optblas<matrix_t> << std::endl;
```

For double, optimized blas is being used, but for legacymatrix, the result is false. I think there might be a problem with the plugin.

**Comment by langou** [comment]
Thanks @thijssteel. It would be great if this turns out to be the issue.

**Comment by weslleyspereira** [comment]
Oh! Ok, my bad. I will use your example to create more tests. Thanks a bunch!

**Comment by thijssteel** [comment]
@langou if by "the issue" you mean the poor performance of gghd3, that can't be it, i already forced the use of optimized blas during my tests.

**Comment by langou** [comment]
Ah. Shoo. Yes, this is what I meant.
