### ISSUE TITLE
small fixed size matrices/vectors on the stack

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#288]
Creating a new vector, currently requires std::vector to be used in the create functor.

Some routines require a small, fixed size, amount of workspace that is normally allocated on the stack, but std::vector is (i think) always on the heap.

For example, my QR and QZ implementations currently use this:
https://github.com/tlapack/tlapack/blob/master/include/tlapack/lapack/lahqr.hpp#L295

It would be nice to be able to wrap a fixed size array to interpret it as a vector.

**Comment by weslleyspereira** [comment]
Hi. I see your point there and I like your idea. So, I suggest we add the following functions to `CreateFunctor`:

```c++
template <typename T, idx_t M, idx_t N>
constexpr auto operator()(T* v) const;

template <typename T, idx_t N>
constexpr auto operator()(T* v) const;
```

We would call it like:

``c++
float v_[3];
auto v = new_vector<3>(v_); 
```

This would be intended for small matrices and vectors only because data-owning classes like `Eigen::Matrix` would need to duplicate the allocated size on the stack. I currently don't now a general strategy that would avoid this duplication of memory.

I can work that feature if you like. It should  go fast.
