### ISSUE TITLE
Fix LARF so that we do not have to edit A(i,i) to be one

### ISSUE THREAD

**Issue by langou** [tlapack/tlapack#35]
I was reviewing @thijssteel PR#34 file gehd2.hpp, and I want to make a comment about larf.hpp. I have the same comment for geqr2.hpp. See: https://github.com/tlapack/tlapack/blob/a81590bada5b5424147175d24e1473f40f94771e/include/lapack/geqr2.hpp#L88

We should edit larf.hpp so that larf.hpp does not access A(i,i). 

A(i,i) in geqr2.hpp is v[0] in larf.hpp. 

v[0] should be one and we should not access it. We should assume that v[0] is one and go with it. 

The writing of v[0] = one in the routine that calls is an issue makes other parent routines not thread friendly. This happens more in larfb.hpp, ormqr.hpp, etc.

Let us fix this in larf.hpp to start with and then edit gehd2.hpp and geqr2.hpp accordingly. That would be a good start.

I understand that it is better to call ( one gemv.hpp and one ger.hpp ) instead of ( one gemv.hpp and one ger.hpp and one axpy.hpp, I think ), but the improved functionality is worth it in my opinion. 

The code would be cleaner and this is important for thread friendliness. 

One example of a related issue is: https://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=2&t=867

**Comment by thijssteel** [comment]
For some more code cleanliness, does it also make sense to change `larfg(alpha, x, ...)` to `larfg(v, ...)`? I can't think of any examples where alpha would not just be v[0].

**Comment by langou** [comment]
I also wondered why this design for larfg for many years. And it serendipitously came super super handy, when we worked on the "tile algorithms". This design is also useful for "update algorithms". This enables to easily create the kernel ``triangle on top of pentagon``.

Let me explain with one example. You have 3,000-by-10 matrix A1, you do GEQRF of A1. You get a 10-by-10 R-factor R1. Good. Now, you have 100 more rows of new observations that come your way, call them 100-by-10 matrix A2, so you want to update the R factor. What you need to do is the 110-by-10 QR factorization of the 10-by-10 upper triangular R1 on top of the 100-by-10 A1. We call this kernel ``triangle-on-top-of-square``. In that example you can see that it is very convenient to have alpha separated from x. At step k, we want alpha to be R1(k,k) and x to be A1(1:100,k). We can do this super easily with current larfg. This is also useful for tile algorithms. Standard kernels are `triangle-on-top-of-square`` and `triangle-on-top-of-triangle``. The kernel in LAPACK that does both is xTPQRT (for triangle on top of pentagon). (So that the pentagon can be a triangle, a rectangle or a true pentagon.)

Since data location is less important for <T>LAPACK, we could consider to do the suggested change from @thijssteel (larfg only takes one vector as input) but then, in a ``triangle on top of pentagon`` configuration, we would need to create a new vector v at each step k with a mapping v[0] = R1(k,k) and v[1] = A1(1,k), v[2] = A1(2,k), etc. And I guess that would work.

**Comment by thijssteel** [comment]
Maybe the best option is to overload it, so we have the main implementation as 
`larfg(alpha, x, ...)` and then `larfg(v, ...)` just calls `larfg(v[0], v[1:n])` (with a check to see if v[1:n] is not out of bounds).

Then we don't need new copies for "triangle-on-top-of-square", users who are translating legacy code can still use the "old" api.
On top of that, it makes the solution for Issue #31 much cleaner.

**Comment by langou** [comment]
"Maybe the best option is to overload it". Good idea. I had not thought about it. Good idea. Yes, indeed. Overloading gives us the best of both world. OK.
