### ISSUE TITLE
Issue with CMakeLists.txt during configuration step

### ISSUE THREAD

**Issue by rileyjmurray** [tlapack/tlapack#4]
Hi there, @weslleyspereira  and @langou! I just installed tlapack and got the example "geqr2" to work, but I had some hiccups in the installation process and I had to edit ``CMakeLists.txt`` to get things to work. Can one of you take a look below and let me know if you think those edits were avoidable?

Here's the full context of the configuration step:
```
(base) riley@borneophant:~/Documents/Research/tlapack/tlapack$ cmake -B build -D CMAKE_INSTALL_PREFIX=~/Documents/Reserch/tlapack/tlapack .
-- <T>LAPACK version 0.1.1
-- testBLAS not found. Trying to fetch from https://github.com/tlapack/testBLAS.git. It may take a while.
-- testBLAS version 0.1.2
-- Catch2 not found. Trying to fetch from https://github.com/catchorg/Catch2.git. It may take a while.
-- Using Catch2 from https://github.com/catchorg/Catch2.git.
-- Using testBLAS from https://github.com/tlapack/testBLAS.git.
CMake Error at CMakeLists.txt:197 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "ARCHIVE_OUTPUT_DIRECTORY" is not allowed.


CMake Error at CMakeLists.txt:197 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LIBRARY_OUTPUT_DIRECTORY" is not allowed.


-- Configuring incomplete, errors occurred!
See also "/home/riley/Documents/Research/tlapack/tlapack/build/CMakeFiles/CMakeOutput.log".
```
I really don't know what to make of that message. Grasping at straws, I just commented out these lines in ``CMakeLists.txt``:
https://github.com/tlapack/tlapack/blob/ee39c930511b4f06545c691f5246338ff96646c2/CMakeLists.txt#L197-L200

It turns out, that worked!  I was able to finish the configuration step and execute the other commands
```
cmake --build build
cmake --build build --target install
```
without problems.

**Comment by weslleyspereira** [comment]
Hi @rileyjmurray. Thanks for noticing that! Your solution works, although it changes the place the libraries will be installed. Instead, I suggest we remove tlapack from the installable libs in this line:

https://github.com/tlapack/tlapack/blob/ee39c930511b4f06545c691f5246338ff96646c2/CMakeLists.txt#L34

Currently, tlapack is just an interface, not a physical library.

What do you think?

**Comment by rileyjmurray** [comment]
I just tried out that change, and it worked great! Thanks, @weslleyspereira!

I'll leave this issue open and you can close it when you make your proposed change.
