### ISSUE TITLE
Out of bounds access in larfb

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#47]
Larfb has an out of bounds access if m == k (i.e. there is only the triangular part of V and V2 is of size zero)

larfb also misses a lot of input checks

**Comment by thijssteel** [comment]
and to be clear, this isn't a problematic out of bounds access, it's similar as we had before in geqr2

**Comment by weslleyspereira** [comment]
I thought b6bf86f26c2297e7e0a6f2cf46b3a06583be6516 fixed the out of bounds on larfb. Can you point it out so I can fix it? Thanks

**Comment by thijssteel** [comment]
my branch is behind on master, my bad
