### ISSUE TITLE
Add a way to construct matrices given a pointer and dimensions

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#64]
We should have a function like:

```c++
    template< class matrix_t >
    inline constexpr matrix_t construct_matrix( type_t<matrix_t> * ptr, size_type<matrix_t> m, size_type<matrix_t> n );
```

so that we can call

```c++
    auto work = construct_matrix<matrix_t>( &work[0], m, n ); 
```
or maybe even
```c++
    matrix_t work = construct_matrix( &work[0], m, n ); 
```

for vectors, maybe we can just generically do:

```c++
     template< typename matrix_t >
     inline auto construct_vector(  type_t<matrix_t> * ptr, size_type<matrix_t> n){
         auto temp = construct_matrix( ptr,  n, 1);
         return col(temp, 0);
     }
```

to avoid having to define a different function for each matrix type

@weslleyspereira I tried implementing it, but since you wrote all those plugins, maybe you'll be better at it.

**Comment by thijssteel** [comment]
Result of discussion with @langou :

We shouldn't assume that an m x n matrix always takes up the same amount of space. For example, a sparse matrix or larger leading dimension to be a multiple of 32.

A function that queries the size in bytes for an m by n matrix of a given type can solve this

**Comment by weslleyspereira** [comment]
This was implemented in https://github.com/tlapack/tlapack/pull/128.
