### ISSUE TITLE
We allow different matrix types, but always test with the same

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#88]
for example, gemm can accept three different types for its three matrices, but the way we are testing now, we only test with the same matrix type (i think).

a similar issue is that we only test for arithmetic types of the same type of the matrix.

However, testing everything would quickly lead to a combinatorial explosion. Not sure what we should do.

**Comment by langou** [comment]
"for example, gemm can accept three different types for its three matrices, but the way we are testing now, we only test with the same matrix type (i think)."

I think this is fine to not test. 

I think we want to be clear that (for now) the behavior of a <T>LAPACK GEMM call with A is "unsigned int", B is "MPFR 256-bit real", and C is "complex float" (for example) is "undefined". And while users can certainly call GEMM with this input data, we do not make any guarantee on what the output is.

At this point, we are only supporting and testing for consistent and limited set of scalar types in the interfaces. These scalar types are the 2 real types float and double, and then the 2 associated complex types. I think that's it for now.

In the future, I would like us to support more types (bfloat16, long double, ARPREC, MPFR, etc.) We will see which in the future.

I think we are a long way to guarantee anything when users are mixing types in the interfaces. 

I do understand that there is some hypocrisy in the sense that we are mixing types in the interface when we do GEMM( NoTrans, NoTrans, 1, A, B, 1, C) where 1 is int, and A, B and C are type T, but I think that's about it that we might want to support. A few scalars in the interface can be of other types. Maybe we can write what is supported there and what best practice for these scalars is.

**Comment by langou** [comment]
"a similar issue is that we only test for arithmetic types of the same type of the matrix." => What do you mean?

**Comment by weslleyspereira** [comment]
Hi. That is a good idea!

I come back yesterday to the branch with the new workspace design. The is my top priority now. With the new design, we will have the `Create<work_t>` functors, so it should be easy to test other matrix data types.

For the CI, we could have one entry that downloads and install Eigen, and then enables test with Eigen data types. The same for every other matrix structure. The same for every other floating-point type, like multiprecision and non-IEEE-standard precision (e.g., bfloat16). We could explore tiled layouts with kokkos::mdspan. 

@langou once suggested we test some unusual data types (Galois field) and unusual layouts (E. Elmroth, F. G. Gustavson, I. Jonsson, and B. K ̊agstro ̈m, Recursive blocked algorithms and hybrid data structures for dense matrix library software, SIAM Review, 46 (2004), pp. 3–45.). I think we would need more time for implementing those.
