### ISSUE TITLE
move debug utils to .cpp

### ISSUE THREAD

**Issue by thijssteel** [tlapack/tlapack#96]
Since they define functions, not templated headers, the debug utils should be in a cpp, or at least the specific function instantiations should be.

**Comment by weslleyspereira** [comment]
I was thinking on how to do it in practice. I think we should create a testutils.cpp and put the wrappers from debugutils.hpp there. My thoughts:

1. We provide the template and the user creates a wrapper if needed. For example, one need would be for debugging with GDB for a specific matrix class, with a given layout, data type, etc.

2. A use case for debugutils.hpp would be: "Someone is developing a tester for a new functionality. They see the test is giving him unexpected results at runtime. The error is associated to a specific matrix class. The developer includes the header debugutils.hpp in his code. If it is a problem associated to instantiations of legacyMatrix, they will have wrappers for the functionality in debugutils.hpp. If it is not, they create the wrapper for the type needed. The developer builds the code in debug mode. They run the code using a debugger and use the wrappers for `print_matrix` and `visualize_matrix`. They then find and fix their code. The inclusion of debugutils.hpp can be removed or commented out".

**Comment by thijssteel** [comment]
And even more practical... how do we get cmake to link with the cpp file? I'm not really familiar with cmake.

**Comment by weslleyspereira** [comment]
> And even more practical... how do we get cmake to link with the cpp file? I'm not really familiar with cmake.

It is not complicated. You can:
1. `add_library(debugutils debugutils.cpp)` and then use this library in the executable `target_link_libraries(test_lasy2 debugutils)`.
2. Or put the .cpp directly in the executable `add_executable(test_lasy2 test_lasy2.cpp debugutils.cpp)`
3. Or do 1 and add it to multiple executables at the same time: https://github.com/tlapack/tlapack/blob/f861d8deeea44451d509b52720cbd08403a1530c/test/src/CMakeLists.txt
